client_id: "xxx"
client_secret: "xxx"
authorize_url: "https://login.live.com/oauth20_authorize.srf"
token_url: "https://login.live.com/oauth20_token.srf"
options:
 scope: "onedrive.readwrite offline_access"
token_type: "account"
